# Generated by Django 4.1 on 2022-08-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='tempo_durcao',
            field=models.DateField(blank=True),
        ),
    ]
