# Generated by Django 4.1 on 2022-08-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_rename_tempo_durcao_emprestimos_tempo_duracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
